# apps/web/shopify.web.toml
name = "web"
roles = ["frontend"]
auth_callback_path = ["/api/auth/callback"]
# If you add a separate backend later, you’ll create another web.toml with roles=["backend"].
# For now, Next.js serves everything.

[commands]
dev = "pnpm dev"
build = "pnpm build"

# Optional (helps the CLI detect your server if you prefer a fixed port)
port = 3000