name: ci-weekly-graphql

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'weekly/week-04/**'
      - 'docs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint web
        run: pnpm --filter @jazm/web lint
      - name: Build @jazm/web
        working-directory: apps/web
        env:
          NODE_ENV: production
          SHOPIFY_APP_URL: 'http://localhost:3000'
          SHOPIFY_API_KEY: 'ci_dummy_key'
          SHOPIFY_API_SECRET: 'ci_dummy_secret'
          SHOPIFY_SCOPES: 'read_products'
          NEXT_PUBLIC_SHOPIFY_API_KEY: 'ci_dummy_key'
        run: pnpm build
      - name: Unit tests (Vitest)
        run: pnpm --filter @jazm/web test:unit
